version: "3.5"

networks:
  traefik-net:
    external: true

services:
  meetup:
    image: strapdata/openfoodfacts:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.backend: meetup
        traefik.frontend.rule: "Host:meetup.903403a9-617f-47ac-933e-537a73091e54.azure.strapcloud.com"
        traefik.docker.network: traefik-net
        traefik.port: 5000
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /etc/docker-context.sh
        target: /etc/profile.d/docker-context.sh
        read_only: true
      - type: bind
        source: /home/centos/.cassandra/cqlshrc
        target: /root/.cassandra/cqlshrc
        read_only: true
      - type: bind
        source: /etc/cassandra/cacert.pem
        target: /cacert.pem
        read_only: true
    environment:
      ELASSANDRA_CERTFILE: "/cacert.pem"
      ELASSANDRA_LOAD_CQLSHRC: "true"
      ELASSANDRA_RF: "2"
      DEBUG: "true"

