version: "3.5"

networks:
  main:

services:
  meetup:
    image: strapdata/openfoodfacts:0.1
    networks:
      - main
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /Users/vroyer/.cassandra/cqlshrc
        target: /root/.cassandra/cqlshrc
        read_only: true
    environment:
      ELASSANDRA_ENDPOINTS: "docker.for.mac.host.internal"
      ELASSANDRA_LOAD_CQLSHRC: "true"
   
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    networks:
      - main
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://docker.for.mac.host.internal:9200
#      elassandra_kibana_password: "kibana"