version: "3.5"

networks:
  traefik-net:
    external: true

services:
  import:
    image: strapdata/openfoodfacts:0.2
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints: [node.hostname == c-903403a9-0]
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /etc/docker-context.sh
        target: /etc/profile.d/docker-context.sh
        read_only: true
      - type: bind
        source: /home/centos/.cassandra/cqlshrc
        target: /root/.cassandra/cqlshrc
        read_only: true
      - type: bind
        source: /etc/cassandra/cacert.pem
        target: /cacert.pem
        read_only: true
      - type: bind
        source: ./fr.openfoodfacts.org.products.csv
        target: /fr.openfoodfacts.org.products.csv
        read_only: true
    environment:
      ELASSANDRA_CERTFILE: "/cacert.pem"
      ELASSANDRA_LOAD_CQLSHRC: "true"
      ELASSANDRA_RF_MAP: '{"DC1": 2, "DC2": 1}'
      ELASSANDRA_LOCAL_DC: "DC1"
      ELASSANDRA_KEYSPACE: "meetup2"
      DEBUG: "true"
      PYTHON_MODULE: "meetup.import"
      #CSV_PATH_OR_URL: "https://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.csv"
      CSV_PATH_OR_URL: "/fr.openfoodfacts.org.products.csv"
      #IMPORT_START_FROM: 224500
